### ISSUE TITLE
ЧтениеZIPАрхива не может прочитать zip присылаемый платформой 8.3.18 с данными отчета об ошибке

### ISSUE THREAD

**Issue by sfaqer** [EvilBeaver/OneScript#1020]
**Опишите ошибку**
ЧтениеZIPАрхива падает в ошибку при попытке прочитать zip файл присылаемый платформой 8.3.18 с данными отчета об ошибке

**Воспроизведение ошибки**
1. Равзернуть https://github.com/sfaqer/ErorrHandlerService
2. Сделать тестовую базу, и указать в ней настройки:
![image](https://user-images.githubusercontent.com/32082417/88761180-f6e76d80-d1b1-11ea-9c50-7340531a2223.png)
3. В тестовой базе вызвать исключение каким угодно образом, отправить отчет
4. В логах работы сервиса из п.1 увидеть ошибку.

**Ожидаемое поведение**
Архив корректно разибрается

**Окружение**
 - ОС: Docker OSWeb 0.7.0
 - Версия: OSWeb 0.7.0, затрудняюсь ответить какая там версия OneScript

**Дополнительная информация**
Стек трейс:

```
handler_1  | fail: Microsoft.AspNetCore.Server.Kestrel[13]
handler_1  |       Connection id "0HM1JG5QF596S", Request id "0HM1JG5QF596S:00000001": An unhandled exception was thrown by the application.
handler_1  | ScriptEngine.Machine.ExternalSystemException: {Модуль /app/controllers/mainController/module.os / Ошибка в строке: 32 / Внешнее исключение (Ionic.Zip.ZipException): Cannot read that as a ZipFile}
 ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0xFE17F92F) at position 0x00000343
handler_1  |    at Ionic.Zip.ZipEntry.ReadDirEntry(ZipFile zf, Dictionary`2 previouslySeen)
handler_1  |    at Ionic.Zip.ZipFile.ReadCentralDirectory(ZipFile zf)
handler_1  |    at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
handler_1  |    --- End of inner exception stack trace ---
handler_1  |    at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
handler_1  |    at Ionic.Zip.ZipFile.Read(String fileName, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress)
handler_1  |    at ScriptEngine.HostedScript.Library.Zip.ZipReader.Open(String filename, String password, FileNamesEncodingInZipFile encoding) in /app/Include/OneScript/src/ScriptEngine.HostedScript/Library/Zip/ZipReader.cs:line 49
handler_1  |    at ScriptEngine.HostedScript.Library.Zip.ZipReader.ConstructByNameAndPassword(IValue filename, IValue password) in /app/Include/OneScript/src/ScriptEngine.HostedScript/Library/Zip/ZipReader.cs:line 147
handler_1  |    at ScriptEngine.Machine.MachineInstance.NewInstance(Int32 argCount) in /app/Include/OneScript/src/ScriptEngine/Machine/MachineInstance.cs:line 1255
handler_1  |    at ScriptEngine.Machine.MachineInstance.MainCommandLoop() in /app/Include/OneScript/src/ScriptEngine/Machine/MachineInstance.cs:line 481
handler_1  |    --- End of inner exception stack trace ---
handler_1  |    at ScriptEngine.Machine.MachineInstance.MainCommandLoop() in /app/Include/OneScript/src/ScriptEngine/Machine/MachineInstance.cs:line 500
handler_1  |    at ScriptEngine.Machine.MachineInstance.ExecuteCode() in /app/Include/OneScript/src/ScriptEngine/Machine/MachineInstance.cs:line 401
handler_1  |    at ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, Int32 methodIndex, IValue[] arguments) in /app/Include/OneScript/src/ScriptEngine/Machine/MachineInstance.cs:line 129
handler_1  |    at ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(Int32 methodNumber, IValue[] arguments, IValue& retValue) in /app/Include/OneScript/src/ScriptEngine/Machine/Contexts/ScriptDrivenObject.cs:line 357
handler_1  |    at ScriptEngine.Machine.Contexts.ReflectedMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /app/Include/OneScript/src/ScriptEngine/Machine/Reflection/ReflectedMethodInfo.cs:line 113
handler_1  |    at OneScript.WebHost.Application.ScriptedController.VoidAction(Object[] parameters) in /app/OneScript/Application/ScriptedController.cs:line 65
handler_1  |    at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
handler_1  |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
handler_1  |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
handler_1  |    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
handler_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Файл архива: [event.zip](https://github.com/EvilBeaver/OneScript/files/4992802/event.zip)

**Comment by sfaqer** [comment]
Ошибка на стороне логики работы с данными передаваемыми платформой
