### ISSUE TITLE
Ошибка в командной строки при любом вызове opm.

### ISSUE THREAD

**Issue by r-khusiainov** [EvilBeaver/OneScript#1183]
Установлен OneScript 1.8.0.3

Запускаю командную строку под администратором, пишу любые команды 
opm
opm -v 
opm install gitsync

Ошибка:

System.TypeInitializationException: The type initializer for 'ScriptEngine.Compi
ler.Compiler' threw an exception. ---> System.TypeInitializationException: The t
ype initializer for 'ScriptEngine.Machine.BuiltinFunctions' threw an exception.
---> System.MissingMethodException: Method not found: '!!0[] System.Array.Empty(
)'.
   at ScriptEngine.Machine.BuiltinFunctions.InitParametersInfo()
   at ScriptEngine.Machine.BuiltinFunctions..cctor()
   --- End of inner exception stack trace ---
   at ScriptEngine.Machine.BuiltinFunctions.GetOperationCodes()
   at ScriptEngine.Compiler.Compiler..cctor()
   --- End of inner exception stack trace ---
   at ScriptEngine.Compiler.Compiler..ctor()
   at ScriptEngine.CompilerService.CompileInternal(ICodeSource source)
   at ScriptEngine.CompilerService.Compile(ICodeSource source)
   at ScriptEngine.HostedScript.HostedScriptEngine.CreateProcess(IHostApplicatio
n host, ICodeSource src)
   at oscript.ExecuteScriptBehavior.Execute()

**Окружение**
 - ОС: Windows Server 2008 R2 Standart Service Pack 1

**Comment by EvilBeaver** [comment]
Версия дотнета какая на машине стоит? Нужна 4.8 https://oscript.io/downloads/archive/1_8_0

**Comment by r-khusiainov** [comment]
Спасибо установка 4.8 помогла.
