### ISSUE TITLE
v2 native: не компилируются некоторые операции для явно объявленной переменной

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1200]
**Опишите ошибку**
Не компилируется сравнение объявленной переменной со строкой

**Воспроизведение ошибки**
1. Запустить код ...
```bsl
#native
Перем Стр;
Стр = "1";
Если Стр = "2" Тогда
КонецЕсли;
```
2. Увидеть ошибку
_Ошибка в строке: 4,1 / Ошибка компиляции статического модуля
System.ArgumentException: Expression of type 'System.String' cannot be used for parameter of type 'OneScript.Values.BslValue' of method 'System.Decimal ToNumber(OneScript.Values.BslValue)' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at OneScript.Native.Compiler.ExpressionHelpers.ToNumber(Expression right) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\ExpressionHelpers.cs:line 117
   at OneScript.Native.Compiler.BinaryOperationCompiler.CompileDynamicOperation(Expression left, Expression right) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\BinaryOperationCompiler.cs:line 255
   at OneScript.Native.Compiler.BinaryOperationCompiler.Compile(BinaryOperationNode node, Expression left, Expression right) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\BinaryOperationCompiler.cs:line 28
   at OneScript.Native.Compiler.MethodCompiler.CompileBinaryOp(Expression left, Expression right, BinaryOperationNode binaryOperationNode) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 640
   at OneScript.Native.Compiler.MethodCompiler.VisitBinaryOperation(BinaryOperationNode binaryOperationNode) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 483
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_2(BslSyntaxNode x) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 37
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 490
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 227
   at OneScript.Native.Compiler.MethodCompiler.ConvertToExpressionTree(BslSyntaxNode arg) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 1447
   at OneScript.Native.Compiler.MethodCompiler.VisitIfExpression(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 731
   at OneScript.Native.Compiler.MethodCompiler.VisitIfNode(ConditionNode node) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 671
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_5(BslSyntaxNode x) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 41
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 490
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 162
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 163}_

**Окружение**
 - Версия: последняя, включающая dc1f358 

**Дополнительная информация**
Если убрать `Перем Стр;` или поменять сравнение на `Если Стр = 2 Тогда`, то работает.
Та же ошибка при замене `Если...` на `Рез = (Стр <> "2");`
Перемещение кода из модуля в процедуру не влияет.

**Update**
Что-то не то с преобразованием типов для объявленной переменной:

```bsl
#native
Перем Индекс;
Индекс = 1;
Символ = Сред("АБВ", Индекс, 1);
```
_Ошибка в строке: 4,8 / Ошибка компиляции статического модуля
System.ArgumentException: Expression of type 'System.Decimal' cannot be used for parameter of type 'System.Int32' of method 'System.String Mid(System.String, Int32, Int32)' (Parameter 'arg1')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1, Expression arg2)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, IEnumerable`1 arguments)
   at OneScript.Native.Compiler.MethodCompiler.CreateBuiltInFunctionCall(CallNode node) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 1268
   at OneScript.Native.Compiler.MethodCompiler.VisitGlobalFunctionCall(CallNode node) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 1048
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_1(BslSyntaxNode x) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 36
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 490
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 227
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 179
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 416
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 490
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 162
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 163}_

Если убрать `Перем Индекс;`, то работает.

**Comment by Mr-Rm** [comment]
А еще вот такой вариант:
```bsl
#native
Перем Индекс; // если убрать - работает
Для Индекс = 0 По 1 Цикл
КонецЦикла;
```
_Ошибка в строке: 3,5 / Ошибка компиляции статического модуля
System.ArgumentException: Expression of type 'System.Decimal' cannot be used for assignment to type 'ScriptEngine.Machine.IValue'
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at OneScript.Native.Compiler.MethodCompiler.VisitForLoopNode(ForLoopNode node) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 842
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_7(BslSyntaxNode x) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 43
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 490
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement) in S:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 162
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 163}_

**Comment by Mr-Rm** [comment]
Как кажется, первоначальная проблема в том, что обращение к объявленной переменной компилируется в узел `MemberAccess.Expression{$this.State[<индекс>]}`, а к необъявленной - `Parameter.Name{"<имя>"}`

**Comment by Mr-Rm** [comment]
Это падает в runtime:
```bsl
#native
Процедура Проц()
   Перем Лок;  // если убрать - работает
   Лок = 0;
   Если Лок > 1 Тогда // или вместо Если, например, `Рез = (Лок = 1);` 
   КонецЕсли;
КонецПроцедуры

Проц();
```
_System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method18(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args) in S:\_Repo\OneScript\src\OneScript.Native\Runtime\CallableMethod.cs:line 46
   at lambda_method19(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args) in S:\_Repo\OneScript\src\OneScript.Native\Runtime\CallableMethod.cs:line 46
   at OneScript.Native.Runtime.BslNativeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in S:\_Repo\OneScript\src\OneScript.Native\Runtime\BslNativeMethodInfo.cs:line 51
   at OneScript.Native.Runtime.NativeExecutorProvider.Executor(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments) in S:\_Repo\OneScript\src\OneScript.Native\Runtime\NativeExecutorProvider.cs:line 48
   at OneScript.Execution.ExecutionDispatcher.Execute(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments) in S:\_Repo\OneScript\src\OneScript.Core\Execution\ExecutionDispatcher.cs:line 43
   at OneScript.Execution.ExecutionExtensions.ExecuteModuleBody(ExecutionDispatcher dispatcher, BslObjectValue target, IExecutableModule module) in S:\_Repo\OneScript\src\OneScript.Core\Execution\ExecutionExtensions.cs:line 21
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.OnInstanceCreation() in S:\_Repo\OneScript\src\ScriptEngine\Machine\Contexts\ScriptDrivenObject.cs:line 120
   at ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation() in S:\_Repo\OneScript\src\ScriptEngine\Machine\Contexts\UserScriptContextInstance.cs:line 57
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.Initialize() in S:\_Repo\OneScript\src\ScriptEngine\Machine\Contexts\ScriptDrivenObject.cs:line 130
   at ScriptEngine.ScriptingEngine.InitializeSDO(ScriptDrivenObject sdo) in S:\_Repo\OneScript\src\ScriptEngine\ScriptingEngine.cs:line 173
   at ScriptEngine.ScriptingEngine.NewObject(IExecutableModule module, ExternalContextData externalContext) in S:\_Repo\OneScript\src\ScriptEngine\ScriptingEngine.cs:line 145
   at ScriptEngine.HostedScript.Process.Start() in S:\_Repo\OneScript\src\ScriptEngine.HostedScript\Process.cs:line 35_

**Comment by EvilBeaver** [comment]
> Как кажется, первоначальная проблема в том, что обращение к объявленной переменной компилируется в узел MemberAccess.Expression{$this.State[<индекс>]}, а к необъявленной - Parameter.Name{"<имя>"}

Это само по себе ошибка, связанная с тем что СкомпилированныйФрагмент был написан первым и он все "внешние" переменные считает параметрами. Но это другая ошибка, как мне кажется, не та, что в описании issue

**Comment by EvilBeaver** [comment]
Короче говоря, взаимодействие "вариантов" с примитивными типами не работает.

**Comment by Mr-Rm** [comment]
Еще падающий вариант, который работает без объявления переменной:
```bsl
#native
Процедура Проц()
	Перем Таблица;
	Таблица = Новый ТаблицаЗначений;
	Таблица.Колонки.Добавить("Имя", Новый ОписаниеТипов("Строка"));
КонецПроцедуры
```
_Ошибка в строке: 5,17 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль C:\_lab\OneScript2\native.os / Ошибка в строке: 5,26 / Тип System.Object не является объектным типом.}    
Таблица.Колонки.Добавить("Имя", Новый ОписаниеТипов("Строка"));
...
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectProcedureCall(BslSyntaxNode node) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 1098
..._
То же, если `Перем Таблица;` объявлена на уровне модуля.

**Comment by EvilBeaver** [comment]
@Mr-Rm Завел последнее отдельной ошибкой

**Comment by Mr-Rm** [comment]
Асимметрия сравнений на равенство/неравенство:
```bsl
#native
Перем Стр1;
Стр1 = "??";
Если Стр1 = "ОК" Тогда
КонецЕсли;
Если "Не ОК" = Стр1 Тогда
КонецЕсли
```
_Ошибка в строке: 6,1 / Ошибка компиляции статического модуля
System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.String' and 'OneScript.Values.BslValue'.
   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
..._
То же для `<>`.
То же для булева и чисел, но неравенства (`< <= > >=`) для чисел работают.

**Comment by Mr-Rm** [comment]
Все отмечаемые ошибки проявляются в том числе и для переменных-параметров:
```bsl
#native
Функция СменитьЗнак(Пар)
	Рез = -Пар;
	Возврат Рез;
КонецФункции
```
_Ошибка в строке: 3,6 / Ошибка компиляции статического модуля
System.InvalidOperationException: The unary operator Negate is not defined for the type 'OneScript.Values.BslValue'.
   at System.Linq.Expressions.Expression.GetUserDefinedUnaryOperatorOrThrow(ExpressionType unaryType, String name, Expression operand)
   at System.Linq.Expressions.Expression.Negate(Expression expression, MethodInfo method)
   at System.Linq.Expressions.Expression.MakeUnary(ExpressionType unaryType, Expression operand, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.MakeUnary(ExpressionType unaryType, Expression operand, Type type)
   at OneScript.Native.Compiler.MethodCompiler.VisitUnaryOperation(UnaryOperationNode unaryOperationNode) in S:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 504
..._
или элементов массива:
```bsl
#native
Массив = Новый Массив;
Массив.Добавить(1);
Рез = -Массив[0];
```
Словом, везде, где нетипизированное `BslValue`

**Comment by EvilBeaver** [comment]
Да, это так и будет, дело не в Перем, а в обработке нетипизированых

**Comment by EvilBeaver** [comment]
Вообще, я вспомнил, что собирался сделать это не багом а фичей. Неизвестный BslValue не должен был автоматически каститься к тому или иному типу....
