### ISSUE TITLE
Native. Ошибка компиляции

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/OneScript#1257]
Ошибка компиляции приложенных файлов в режиме native

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at OneScript.Language.IdentifiersTrie`1.Get(String str)
   at OneScript.Language.IdentifiersTrie`1.get_Item(String index)
   at OneScript.Native.Compiler.BuiltInFunctionsCache.GetMethod(String name)
   at OneScript.Native.Compiler.MethodCompiler.CreateBuiltInFunctionCall(CallNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitGlobalFunctionCall(CallNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_1(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Native.Compiler.MethodCompiler.ConvertToExpressionTree(BslSyntaxNode arg)
   at OneScript.Native.Compiler.MethodCompiler.<>c__DisplayClass85_0.<PrepareCallArguments>b__0(BslSyntaxNode passedArg)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at OneScript.Native.Compiler.MethodCompiler.PrepareCallArguments(BslSyntaxNode argList, ParameterInfo[] declaredParameters)
   at OneScript.Native.Compiler.MethodCompiler.CreateMethodCall(CallNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitGlobalFunctionCall(CallNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_1(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Native.Compiler.MethodCompiler.ConvertToExpressionTree(BslSyntaxNode arg)
   at OneScript.Native.Compiler.MethodCompiler.<>c__DisplayClass85_0.<PrepareCallArguments>b__0(BslSyntaxNode passedArg)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at OneScript.Native.Compiler.MethodCompiler.PrepareCallArguments(BslSyntaxNode argList, ParameterInfo[] declaredParameters)
   at OneScript.Native.Compiler.MethodCompiler.CreateMethodCall(CallNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitGlobalFunctionCall(CallNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_1(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Native.Compiler.MethodCompiler.ConvertToExpressionTree(BslSyntaxNode arg)
   at OneScript.Native.Compiler.MethodCompiler.<>c__DisplayClass85_0.<PrepareCallArguments>b__0(BslSyntaxNode passedArg)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at OneScript.Native.Compiler.MethodCompiler.PrepareCallArguments(BslSyntaxNode argList, ParameterInfo[] declaredParameters)
   at OneScript.Native.Compiler.MethodCompiler.CreateMethodCall(CallNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitGlobalProcedureCall(CallNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}
Сообщить(СтрШаблон("%1 Секунд %2   попыток (х 100)", ДополнитьСтроку(Формат(ветстоун.времени, "ЧЦ=11; ЧДЦ=2"), 11, " "), ДополнитьСтроку(Формат(экстра, "ЧЦ=10"), 10, " ")));
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(BilingualString errorText, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitCodeBlock(CodeBatchNode statements)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitCodeBlock(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitWhileBody(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitWhileNode(WhileLoopNode node)
```

**Comment by EvilBeaver** [comment]
[benchmarks.zip](https://github.com/EvilBeaver/OneScript/files/10838510/benchmarks.zip)
