### ISSUE TITLE
ЧтениеДанных на ОС 2.0 #native

### ISSUE THREAD

**Issue by Nivanchenko** [EvilBeaver/OneScript#1274]
`oscript2 -version
2.0.0.341-rc2-27985426`

Вот так работает
```bsl
#native
ЧтениеДанных = Новый ЧтениеДанных("t.os");
```

А вот так не работает
```bsl
#native
ЧтениеДанных = Новый ЧтениеДанных("t.os", КодировкаТекста.UTF8);
```
Стектрейс
```
{Модуль /Users/n.ivanchenko/Documents/tmp/oslog2/t.os / Ошибка в строке: 2,14 / Ошибка компиляции статического модуля
System.ArgumentException: Expression of type 'ScriptEngine.Machine.IValue' cannot be used for parameter of type 'OneScript.Values.BslValue' of method 'OneScript.Values.BslValue GetPropertyValue(OneScript.Values.BslValue, System.String)' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at OneScript.Native.Compiler.ExpressionHelpers.GetContextPropertyValue(Expression target, String propertyName)
   at OneScript.Native.Compiler.MethodCompiler.MakeReadPropertyAccess(TerminalNode operand)
   at OneScript.Native.Compiler.MethodCompiler.VisitResolveProperty(TerminalNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Native.Compiler.MethodCompiler.ConvertToExpressionTree(BslSyntaxNode arg)
   at OneScript.Native.Compiler.MethodCompiler.<VisitNewObjectCreation>b__88_0(BslSyntaxNode passedArg)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OneScript.Native.Compiler.MethodCompiler.VisitNewObjectCreation(NewObjectNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_11(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}
```

**Comment by Nivanchenko** [comment]
В 2.0.0.356-rc3-28069562 заработало.
