### ISSUE TITLE
Набор ошибок в #native

### ISSUE THREAD

**Issue by Nivanchenko** [EvilBeaver/OneScript#1278]
`oscript2 -version 2.0.0.341-rc2-27985426`

На некоторых своих проектах пробовал включать #native, насобирал ряд ошибок. Возможно я не так использую этот режим, или это бай дизигн. 

## Тест ПеречислениеКодировкиТекста.os
Код:
```bsl
#native

Кодировка = КодировкаТекста.UTF8;
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/ПеречислениеКодировкиТекста.os / Ошибка в строке: 3,11 / Ошибка компиляции статического модуля
System.ArgumentException: Expression of type 'ScriptEngine.Machine.IValue' cannot be used for parameter of type 'OneScript.Values.BslValue' of method 'OneScript.Values.BslValue GetPropertyValue(OneScript.Values.BslValue, System.String)' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
   at OneScript.Native.Compiler.ExpressionHelpers.GetContextPropertyValue(Expression target, String propertyName)
   at OneScript.Native.Compiler.MethodCompiler.MakeReadPropertyAccess(TerminalNode operand)
   at OneScript.Native.Compiler.MethodCompiler.VisitResolveProperty(TerminalNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест ПроверкаРаботыСТипом.os
Код:
```bsl
#native

ТипМассив = Тип("Массив");
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/ПроверкаРаботыСТипом.os / Ошибка в строке: 3,11 / Ошибка компиляции статического модуля
System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at OneScript.Native.Compiler.MethodCompiler.ConvertToExpressionTree(BslSyntaxNode arg)
   at OneScript.Native.Compiler.MethodCompiler.CreateBuiltInFunctionCall(CallNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitGlobalFunctionCall(CallNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_1(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест ПодключениеЧерезИспользовать.os
Код:
```bsl
#native
#Использовать "../feature/use/"
ТестовыйСценарий = Новый ТестовыйСценарий;
```

`./feature/use/Классы/ТестовыйСценарий.os`

```bsl
#native

Перем Поле1 Экспорт;

Перем Поле2;

Процедура ПриСозданииОбъекта()
	Поле1 = 1;
КонецПроцедуры


Процедура Метод1()
	
КонецПроцедуры

Процедура Метод2() Экспорт
	
КонецПроцедуры
```

Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/ПодключениеЧерезИспользовать.os / Ошибка в строке: 3,18 / Ошибка компиляции статического модуля
OneScript.Commons.RuntimeException: Тип не зарегистрирован (ТестовыйСценарий)
   at ScriptEngine.Machine.DefaultTypeManager.GetTypeByName(String name)
   at OneScript.Native.Compiler.MethodCompiler.VisitNewObjectCreation(NewObjectNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_11(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест ИзменениеЗначенияПоСсылке.os
Код:
```bsl
#native

Процедура Равно(Знач1, Знач2, Пояснение = "") Экспорт
	Если НЕ Знач1 = Знач2 Тогда
		ВызватьИсключение "Не равны " + Знач1 + " и " + Знач2;
	КонецЕсли;
КонецПроцедуры

Процедура Прибавление(Сумма)
	Сумма = Сумма + 1;
КонецПроцедуры

Параметр = 1;

Прибавление(Параметр);

Равно(Параметр, 2, "Параметр");
```
Ошибка:
```
OneScript.Commons.RuntimeException: Не равны 1 и 2
   at lambda_method18(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args)
   at lambda_method20(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args)
   at OneScript.Native.Runtime.BslNativeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OneScript.Native.Runtime.NativeExecutorProvider.Executor(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionDispatcher.Execute(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionExtensions.ExecuteModuleBody(ExecutionDispatcher dispatcher, BslObjectValue target, IExecutableModule module)
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.Initialize()
   at ScriptEngine.ScriptingEngine.InitializeSDO(ScriptDrivenObject sdo)
   at ScriptEngine.ScriptingEngine.NewObject(IExecutableModule module, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.Process.Start()

```
## Тест РефлекторПоАннотациям.os
Код:
```bsl
// не включаю #native, он включен в feature/reflector/Классы/ТестовыйСценарий.os
#Использовать "../feature/reflector/"

Процедура Равно(Знач1, Знач2) Экспорт
	Если НЕ Знач1 = Знач2 Тогда
		ВызватьИсключение "Не равны " + Знач1 + " и " + Знач2;
	КонецЕсли;
КонецПроцедуры

ТестовыйСценарий = Новый ТестовыйСценарий;

Рефлектор = Новый Рефлектор();

Методы = Рефлектор.ПолучитьТаблицуМетодов(ТестовыйСценарий);
Поля = Рефлектор.ПолучитьТаблицуСвойств(ТестовыйСценарий, Истина);

Равно(Методы.Количество(), 4);
Равно(Поля.Количество(), 2);

Равно(Методы[2].Аннотации[0].Имя, "М1");
Равно(Методы[3].Аннотации[0].Имя, "М2");
Равно(Методы[3].Аннотации[0].Параметры[0].Имя, "знч");
Равно(Методы[3].Аннотации[0].Параметры[0].Значение, 1);

Равно(Поля[0].Аннотации[0].Имя, "П1");
Равно(Поля[1].Аннотации[0].Имя, "П2");
Равно(Поля[1].Аннотации[0].Параметры[0].Имя, "знч");
Равно(Поля[1].Аннотации[0].Параметры[0].Значение, 2);
```

`feature/reflector/Классы/ТестовыйСценарий.os`

```bsl
#native

&П1
Перем Поле1 Экспорт;

&П2(знч = 2)
Перем Поле2;

Процедура ПриСозданииОбъекта()
	Поле1 = 1;
КонецПроцедуры

&М1
Процедура Метод1()
	
КонецПроцедуры

&М2(знч = 1)
Процедура Метод2() Экспорт
	
КонецПроцедуры
```

Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/РефлекторПоАннотациям.os / Ошибка в строке: 14 / Внешнее исключение (System.InvalidCastException): Unable to cast object of type 'OneScript.Language.SyntaxAnalysis.AstNodes.AnnotationNode' to type 'OneScript.Contexts.BslAnnotationAttribute'.}

```
## Тест ПодключениеСценария.os
Код:
```bsl
#native

ПодключитьСценарий("./feature/use/Классы/ТестовыйСценарий.os", "ТестовыйСценарий");

ТестовыйСценарий = Новый ТестовыйСценарий;
```

`./feature/use/Классы/ТестовыйСценарий.os`

```bsl
#native

Перем Поле1 Экспорт;

Перем Поле2;

Процедура ПриСозданииОбъекта()
	Поле1 = 1;
КонецПроцедуры


Процедура Метод1()
	
КонецПроцедуры

Процедура Метод2() Экспорт
	
КонецПроцедуры
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/ПодключениеСценария.os / Ошибка в строке: 5,18 / Ошибка компиляции статического модуля
OneScript.Commons.RuntimeException: Тип не зарегистрирован (ТестовыйСценарий)
   at ScriptEngine.Machine.DefaultTypeManager.GetTypeByName(String name)
   at OneScript.Native.Compiler.MethodCompiler.VisitNewObjectCreation(NewObjectNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_11(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```

**Comment by nixel2007** [comment]
Тест ПодключениеСценария.os два раза

**Comment by Nivanchenko** [comment]
> Тест ПодключениеСценария.os два раза

Не вижу =) есть `Тест ПодключениеЧерезИспользовать.os` и `Тест ПодключениеСценария.os`. Вот они похожи.
У меня еще был косяк с регуляркой в нейтив, но пока на простом примере воспроизвести не получается.

**Comment by Nivanchenko** [comment]
Вот, удалось воспроизвести падение  регулярки. 

## Тест РегулярноеВыражение.os
Код:
```bsl
#Использовать "../feature/regex"

Процедура Равно(Знач1, Знач2) Экспорт
	Если НЕ Знач1 = Знач2 Тогда
		ВызватьИсключение "Не равны " + Знач1 + " и " + Знач2;
	КонецЕсли;
КонецПроцедуры

ИсходнаяСтрока = "{20221110000049,N,
|{2444a6a24da10,3d},1,1,1,1803214,81,I,""Первое событие"",599,
|{""U""},""Представление данных"",1,1,9,3,0,
|{0}
|},
|{20221110000049,U,
|{2444a6a24da10,3d},1,1,1,1803214,81,E,""Второе событие"",599,
|{""U""},""Представление данных2"",1,1,9,3,0,
|{2,1,31,2,31}
|}";
Регулярка =  "\,*\r*\n*\{(\d{14}),(\w),\r*\n\{([0-9a-f]+),([0-9a-f]+)\},(\d+),(\d+),(\d+),(\d+),(\d+),(\w),""([^ꡏ]*?)(?="",\d+,\r*\n)"",(\d+),\r*\n\{([^ꡏ]*?)(?=\},"")\},""([^ꡏ]*?)(?="",\d+)"",(\d+),(\d+),(\d+),(\d+),\d+[,\d+]*,\r*\n\{((\d+)|\d+,(\d+),(\d+),(\d+),(\d+))\}\r*\n\},*\r*\n*";	

ОберткаНадРегуляркой = Новый ОберткаНадРегуляркой(Регулярка);

Совпадения = ОберткаНадРегуляркой.НайтиСовпадения(ИсходнаяСтрока);
Совпадение = Совпадения[0];

Равно(2, Совпадения.Количество());
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/РегулярноеВыражение.os / Ошибка в строке: 23 / Невозможно преобразовать OneScript.StandardLibrary.Regex.MatchCollection в тип BslValue}
```

`feature/regex/Классы/ОберткаНадРегуляркой.os`

```bsl
#native

Перем РегулярноеВыражение;

Процедура ПриСозданииОбъекта(ТекстРегулярки)
	РегулярноеВыражение = Новый РегулярноеВыражение(ТекстРегулярки);	
КонецПроцедуры

Функция НайтиСовпадения(Текст) Экспорт

	КоллекцияСовпадений = РегулярноеВыражение.НайтиСовпадения(Текст);

	Возврат КоллекцияСовпадений;
	
КонецФункции
```

Но если не сохранять объект регулярки в поле, а создавать сразу в `НайтиСовпадения`, тогда не падает.

**Comment by sfaqer** [comment]
Дополню ещё:

# Тест ПроцедураCВозвратом.os

```bsl
#native

Процедура Тест()
	
	Возврат;

КонецПроцедуры
```

Ошибка компиляции:
```
Ошибка в строке: 5,2 / Ошибка компиляции статического модуля
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at OneScript.Native.Compiler.MethodCompiler.VisitReturnNode(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}
```

**Comment by EvilBeaver** [comment]
@Nivanchenko FYI ИзменениеЗначенияПоСсылке.os - в нативе не поддерживается передача по ссылке, только по значению. Пока точно так и задумано

**Comment by EvilBeaver** [comment]
@Nivanchenko все кроме передачи по ссылке (не поддерживается) вроде пофиксил. Можешь еще разок проверить на последней сборке? https://build.oscript.io/job/1Script/job/develop/356/

**Comment by Nivanchenko** [comment]
> @Nivanchenko все кроме передачи по ссылке (не поддерживается) вроде пофиксил. Можешь еще разок проверить на последней сборке? https://build.oscript.io/job/1Script/job/develop/356/

Да, сегодня ближе к ночи проверю 👍

**Comment by Nivanchenko** [comment]
> @Nivanchenko все кроме передачи по ссылке (не поддерживается) вроде пофиксил. Можешь еще разок проверить на последней сборке? https://build.oscript.io/job/1Script/job/develop/356/

Все о чем я писал, работает. Но кажется сломался метод "Количество()" для всех коллекций, которые я сейчас смог вспомнить.


## Тест КоличествоВСтруктуре.os
Код:
```bsl
#native

Коллекция = Новый Структура;

Количество = Коллекция.Количество();
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВСтруктуре.os / Ошибка в строке: 5,12 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВСтруктуре.os / Ошибка в строке: 5,34 / Использование процедуры, как функции}    
Количество = Коллекция.Количество();
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(CodeError err, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectFunctionCall(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест КоличествоВСписокЗначений.os
Код:
```bsl
#native

Коллекция = Новый СписокЗначений();

Количество = Коллекция.Количество();
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВСписокЗначений.os / Ошибка в строке: 5,12 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВСписокЗначений.os / Ошибка в строке: 5,34 / Использование процедуры, как функции}    
Количество = Коллекция.Количество();
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(CodeError err, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectFunctionCall(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест КоличествоВТаблицаЗначений.os
Код:
```bsl
#native

Коллекция = Новый ТаблицаЗначений();

Количество = Коллекция.Количество();
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВТаблицаЗначений.os / Ошибка в строке: 5,12 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВТаблицаЗначений.os / Ошибка в строке: 5,34 / Использование процедуры, как функции}    
Количество = Коллекция.Количество();
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(CodeError err, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectFunctionCall(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест КоличествоВМасиве.os
Код:
```bsl
#native

Массив = Новый Массив();

Количество = Массив.Количество();
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВМасиве.os / Ошибка в строке: 5,12 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВМасиве.os / Ошибка в строке: 5,31 / Использование процедуры, как функции}    
Количество = Массив.Количество();
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(CodeError err, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectFunctionCall(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест КоличествоВСоответствие.os
Код:
```bsl
#native

Коллекция = Новый Соответствие();

Количество = Коллекция.Количество();
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВСоответствие.os / Ошибка в строке: 5,12 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВСоответствие.os / Ошибка в строке: 5,34 / Использование процедуры, как функции}    
Количество = Коллекция.Количество();
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(CodeError err, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectFunctionCall(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест КоличествоВТаблицаЗначенийКолонки.os
Код:
```bsl
#native

Коллекция = Новый ТаблицаЗначений();

Количество = Коллекция.Колонки.Количество();
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВТаблицаЗначенийКолонки.os / Ошибка в строке: 5,12 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/КоличествоВТаблицаЗначенийКолонки.os / Ошибка в строке: 5,42 / Использование процедуры, как функции}    
Количество = Коллекция.Колонки.Количество();
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(CodeError err, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectFunctionCall(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
Тестов не пройдено 6

**Comment by EvilBeaver** [comment]
Исправлено. @dvakor FYI

**Comment by Nivanchenko** [comment]
Отлично, все работает🎉
