### ISSUE TITLE
Параметры по умолчанию для методов #native

### ISSUE THREAD

**Issue by Nivanchenko** [EvilBeaver/OneScript#1289]
Прости =) продолжаю натягивать ОСень на нейтив. Еще болючая штука
## Тест ЗначенияВМетодахПоУмолчанию.os
Код:
```bsl
#native

Функция Сложить(Текст1 = "Т1 ", Текст2 = "Т2 ")
	Сообщить(Текст1);
	Сообщить(Текст2);
	Возврат Текст1 + Текст2;
КонецФункции

Результат = Сложить(,"Текст");

Если НЕ Результат = "Т1 Текст" Тогда
	ВызватьИсключение "Текст сформировался не корректно";
КонецЕсли;
```
Ошибка:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method18(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args)
   at lambda_method19(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args)
   at OneScript.Native.Runtime.BslNativeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OneScript.Native.Runtime.NativeExecutorProvider.Executor(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionDispatcher.Execute(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionExtensions.ExecuteModuleBody(ExecutionDispatcher dispatcher, BslObjectValue target, IExecutableModule module)
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.Initialize()
   at ScriptEngine.ScriptingEngine.InitializeSDO(ScriptDrivenObject sdo)
   at ScriptEngine.ScriptingEngine.NewObject(IExecutableModule module, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.Process.Start()

```

**Comment by EvilBeaver** [comment]
Ты наоборот, пиши больше

**Comment by Nivanchenko** [comment]
Пример выше заработал, когда методы в одном классе. Но как выяснилось, если импортить и инстанцировать другой класс, то ошибка не ушла.

## Тест ЗначенияВМетодахПоУмолчаниюИспользоватьСтрока.os
Код:
```bsl
#native

#Использовать "../feature/use/"

Сценарий = Новый СценарийСПараметрамиПоУмолчанию;

Результат = Сценарий.МетодСтроки(,"Текст");

Если НЕ Результат = "Т1 Текст" Тогда
	ВызватьИсключение "Текст сформировался не корректно";
КонецЕсли;
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/ЗначенияВМетодахПоУмолчаниюИспользоватьСтрока.os / Ошибка в строке: 7,11 / Ошибка компиляции статического модуля
System.ArgumentNullException: Value cannot be null. (Parameter 'arguments[1]')
   at System.Dynamic.Utils.ContractUtils.RequiresNotNull(Object value, String paramName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(Expression expression, String paramName, Int32 idx)
   at System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument(Expression arg, String paramName, Int32 index)
   at System.Linq.Expressions.ExpressionExtension.MakeDynamic(CallSiteBinder binder, Type returnType, ReadOnlyCollection`1 arguments)
   at System.Linq.Expressions.ExpressionExtension.Dynamic(CallSiteBinder binder, Type returnType, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Dynamic(CallSiteBinder binder, Type returnType, IEnumerable`1 arguments)
   at OneScript.Native.Compiler.MethodCompiler.VisitObjectFunctionCall(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperand(BslSyntaxNode operand)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitDereferenceOperation(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```
## Тест ЗначенияВМетодахПоУмолчаниюИспользоватьБулево.os
Код:
```bsl
#native

#Использовать "../feature/use/"

Сценарий = Новый СценарийСПараметрамиПоУмолчанию;

Результат1 = Сценарий.МетодБулево();
Результат2 = Сценарий.МетодБулево(Истина);
Результат3 = Сценарий.МетодБулево(Ложь);

Если НЕ Результат1 = 1 Тогда
	ВызватьИсключение "Ошибка передачи параметра";
КонецЕсли;

Если НЕ Результат2 = 1 Тогда
	ВызватьИсключение "Ошибка передачи параметра";
КонецЕсли;

Если НЕ Результат3 = 0 Тогда
	ВызватьИсключение "Ошибка передачи параметра";
КонецЕсли;
```
Ошибка:
```
OneScript.Commons.TypeConversionException: Преобразование к типу 'Булево' не поддерживается
   at OneScript.Values.BslValue.op_Explicit(BslValue target)
   at lambda_method59(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args)
   at OneScript.Native.Runtime.BslNativeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OneScript.Native.Runtime.NativeExecutorProvider.Executor(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionDispatcher.Execute(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(Int32 methodNumber, IValue[] arguments, IValue& retValue)
   at ScriptEngine.Machine.Contexts.ContextIValueImpl.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , BslValue )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at lambda_method64(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args)
   at OneScript.Native.Runtime.BslNativeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OneScript.Native.Runtime.NativeExecutorProvider.Executor(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionDispatcher.Execute(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionExtensions.ExecuteModuleBody(ExecutionDispatcher dispatcher, BslObjectValue target, IExecutableModule module)
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.Initialize()
   at ScriptEngine.ScriptingEngine.InitializeSDO(ScriptDrivenObject sdo)
   at ScriptEngine.ScriptingEngine.NewObject(IExecutableModule module, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.Process.Start()

```
## Тест ЗначенияВМетодахПоУмолчаниюИспользоватьНеопределено.os
Код:
```bsl
#native

#Использовать "../feature/use/"

Сценарий = Новый СценарийСПараметрамиПоУмолчанию;

Результат1 = Сценарий.МетодНеопределено();
Результат2 = Сценарий.МетодНеопределено(Неопределено);
Результат3 = Сценарий.МетодНеопределено(Ложь);

Если НЕ Результат1 = 1 Тогда
	ВызватьИсключение "Ошибка передачи параметра";
КонецЕсли;

Если НЕ Результат2 = 1 Тогда
	ВызватьИсключение "Ошибка передачи параметра";
КонецЕсли;

Если НЕ Результат3 = 0 Тогда
	ВызватьИсключение "Ошибка передачи параметра";
КонецЕсли;
```
Ошибка:
```
OneScript.Commons.RuntimeException: Ошибка передачи параметра
   at lambda_method64(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args)
   at OneScript.Native.Runtime.BslNativeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OneScript.Native.Runtime.NativeExecutorProvider.Executor(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionDispatcher.Execute(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments)
   at OneScript.Execution.ExecutionExtensions.ExecuteModuleBody(ExecutionDispatcher dispatcher, BslObjectValue target, IExecutableModule module)
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.Initialize()
   at ScriptEngine.ScriptingEngine.InitializeSDO(ScriptDrivenObject sdo)
   at ScriptEngine.ScriptingEngine.NewObject(IExecutableModule module, ExternalContextData externalContext)
   at ScriptEngine.HostedScript.Process.Start()

```

```feature/use/Классы/СценарийСПараметрамиПоУмолчанию.os```
```bsl
#native

Процедура ПриСозданииОбъекта()
	
КонецПроцедуры

Функция МетодСтроки(Текст1 = "Т1 ", Текст2 = "Т2 ") Экспорт
	Возврат Текст1 + Текст2;
КонецФункции

Функция МетодБулево(Булево = Истина) Экспорт
	
	Если Булево = Истина Или Булево Тогда
		Возврат 1;
	Иначе 
		Возврат 0;
	КонецЕсли;

КонецФункции

Функция МетодНеопределено(Параметр = Неопределено) Экспорт
	
	Если Параметр = Неопределено Тогда
		Возврат 1;
	Иначе 
		Возврат 0;
	КонецЕсли;

КонецФункции
```

**Comment by Nivanchenko** [comment]
@Mr-Rm FYI =)

**Comment by Mr-Rm** [comment]
Тогда переоткрыть issue

**Comment by Nivanchenko** [comment]
> Тогда переоткрыть issue

Я не могу =) @EvilBeaver

**Comment by Mr-Rm** [comment]
Все три теста падают на v2 и без `native`:
_ЗначенияВМетодахПоУмолчаниюИспользоватьСтрока.os / Ошибка в строке: 7 / (null) Преобразование к типу 'Число' не поддерживается_

_ЗначенияВМетодахПоУмолчаниюИспользоватьБулево.os / Ошибка в строке: 7 / Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object._

_ЗначенияВМетодахПоУмолчаниюИспользоватьНеопределено.os / Ошибка в строке: 7 / Внешнее исключение (System.NullReferenceException): Object reference not set to an instance of an object._

**Comment by EvilBeaver** [comment]
@Mr-Rm я поправлю

**Comment by Mr-Rm** [comment]
> я поправлю

Для native? Ok, но я продолжу копать, там есть кое-что исправить в том числе и для v1.8

**Comment by EvilBeaver** [comment]
@Mr-Rm предлагаю исправить "кое-что исправить в том числе и для v1.8" отдельной задачей, чтобы эти фиксы @Nivanchenko было проще контролировать

**Comment by Mr-Rm** [comment]
Тест "ЗначенияВМетодахПоУмолчаниюИспользоватьСтрока.os", который с `#Использовать "../feature/use/"` по-прежнему падает.
Стектрейс тот же. Исправленная `BslNativeMethodInfo.Invoke()` не вызывается

**Comment by Nivanchenko** [comment]
> Тест "ЗначенияВМетодахПоУмолчаниюИспользоватьСтрока.os", который с `#Использовать "../feature/use/"` по-прежнему падает. Стектрейс тот же. Исправленная `BslNativeMethodInfo.Invoke()` не вызывается

подтверждаю, падает

**Comment by Mr-Rm** [comment]
Выше ссылка на коммит с моим вариантом исправлений, уже поверх текущих. `BslNativeMethodInfo.Invoke()` вернул как было. Изменения по заполнению дефолтных значений - в ContextIValueImpl.TryInvokeMember() и `MachineInstance.PrepareContextCallArguments()` _(они фактически одинаковые, надо бы вынести их в отдельную функцию)_.
И убран `null` в `MethodCompiler.PrepareDynamicCallArguments()`, из-за которого падало.
Новые тесты проходят.
@EvilBeaver это пока WIP, проверяю.

**Comment by EvilBeaver** [comment]
@Mr-Rm тогда, если все взлетит - просьба влить. Переоткрыл

**Comment by EvilBeaver** [comment]
> `BslNativeMethodInfo.Invoke()` вернул как было.

А это точно не вредно? Вроде бы там тоже надо, если тест `tests\native-lib\test-native-use.os` прогнать, то на нее попадает как раз.

**Comment by Mr-Rm** [comment]
>А это точно не вредно? Вроде бы там тоже надо, если тест tests\native-lib\test-native-use.os прогнать, то на нее попадает как раз.

BslNativeMethodInfo.Invoke() в итоге через CallableObject вызывает ContextIValueImpl.TryInvokeMember(). Пока всё сходилось к нему.

**Comment by Mr-Rm** [comment]
Падало на многочисленных кастингах ...IValue - object -BslValue - system value types...
Сделал PR только с фиксом в native.
