### ISSUE TITLE
Метод Найти() у массива #native

### ISSUE THREAD

**Issue by Nivanchenko** [EvilBeaver/OneScript#1294]
Метод Найти() у массива возвращает число индекса, но в каком-то странном типе, что любые манипуляции с ним роняют компилятор.

## Тест СравнениеСтрокСНеопределено.os
Код:
```bsl
#native

Массив = Новый Массив();
Массив.Добавить("1");
Массив.Добавить("2");
Массив.Добавить("3");

РезультатПоиска = Массив.Найти("1");

Если Массив.Найти("1") <> Неопределено Тогда
	Нашли = Истина;
Иначе
	Нашли = Ложь;
КонецЕсли;

Если Массив.Найти("9") <> Неопределено Тогда
	Нашли = Истина;
Иначе
	Нашли = Ложь;
КонецЕсли;
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/СравнениеСтрокСНеопределено.os / Ошибка в строке: 10,1 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/СравнениеСтрокСНеопределено.os / Ошибка в строке: 10,26 / Преобразование из типа ScriptEngine.Machine.IValue в тип BslValue не поддерживается}    
Если Массив.Найти("1") <> Неопределено Тогда
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err)
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(BilingualString errorText, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.AddError(BilingualString errorText, CodeRange location)
   at OneScript.Native.Compiler.MethodCompiler.CompileBinaryOp(Expression left, Expression right, BinaryOperationNode binaryOperationNode)
   at OneScript.Native.Compiler.MethodCompiler.VisitBinaryOperation(BinaryOperationNode binaryOperationNode)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_2(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression)
   at OneScript.Native.Compiler.MethodCompiler.ConvertToExpressionTree(BslSyntaxNode arg)
   at OneScript.Native.Compiler.MethodCompiler.VisitIfExpression(BslSyntaxNode node)
   at OneScript.Native.Compiler.MethodCompiler.VisitIfNode(ConditionNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_5(BslSyntaxNode x)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node)
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement)
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement)}

```

**Comment by EvilBeaver** [comment]
Да, это известная в общем-то проблема с нетипизированными коллекциями и отсутствием (пока) операторов приведения типов. Никогда не угадаешь, какой тип будет ))

Спасибо, конкретно это - починю.

**Comment by Mr-Rm** [comment]
Чинится исправлением в одной строчке (которое тянет за собой ещё несколько). И native начинает работать.

**Comment by nixel2007** [comment]
Где же этот волшебный пулл реквест? :)

**Comment by Mr-Rm** [comment]
Волшебство будет, когда package-loader в native заработает. Пока только фиксы.

**Comment by Nivanchenko** [comment]
Последний пр(2.0.0.360-rc3-28079013), сломал старые тесты, сюда написать или новую ишузу запилить? @EvilBeaver

**Comment by Nivanchenko** [comment]
Если что могу новый завести =)
## Тест ИзменениеЗначенияПоСсылкеМассив.os
Код:
```bsl
#native

Процедура ДобавитьВМассив(Массив)
	Массив.Добавить(1);
КонецПроцедуры

МойМассив = Новый Массив;

ДобавитьВМассив(МойМассив);

Значение = МойМассив[0];

Если Значение <> 1 Тогда
	ВызватьИсключение "Моссив не изменен";
КонецЕсли;
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/tests/ИзменениеЗначенияПоСсылкеМассив.os / Ошибка в строке: 4,8 / Преобразование из типа System.Object в тип BslValue не поддерживается}

```

**Comment by Nivanchenko** [comment]
## Тест РегулярноеВыражение.os
Код:
```bsl
#Использовать "../feature/regex"

Процедура Равно(Знач1, Знач2) Экспорт
	Если НЕ Знач1 = Знач2 Тогда
		ВызватьИсключение "Не равны " + Знач1 + " и " + Знач2;
	КонецЕсли;
КонецПроцедуры

ИсходнаяСтрока = "456";
Регулярка =  "\d\d\d";

ОберткаНадРегуляркой = Новый ОберткаНадРегуляркой(Регулярка);

Совпадения = ОберткаНадРегуляркой.НайтиСовпадения(ИсходнаяСтрока);

Равно(1, Совпадения.Количество());
```
Ошибка:
```
{Модуль /Users/n.ivanchenko/Documents/repos/oscript-native-test/feature/regex/Классы/ОберткаНадРегуляркой.os / Ошибка в строке: 11,22 / Преобразование из типа System.Object в тип BslValue не поддерживается}

```
feature/regex/Классы/ОберткаНадРегуляркой.os
```bsl
#native

Перем РегулярноеВыражение;

Процедура ПриСозданииОбъекта(ТекстРегулярки)
	РегулярноеВыражение = Новый РегулярноеВыражение(ТекстРегулярки);	
КонецПроцедуры

Функция НайтиСовпадения(Текст) Экспорт

	КоллекцияСовпадений = РегулярноеВыражение.НайтиСовпадения(Текст);

	Возврат КоллекцияСовпадений;
	
КонецФункции
```

**Comment by Mr-Rm** [comment]
Значит, в некоторых случаях прилетает голый object вместо IValue.
Быстрый путь - вернуть заглушку на typeof(object).
