### ISSUE TITLE
v2 natve: значение, возвращаемое функцией `Тип()`

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1301]
**Опишите ошибку**
Значение, возвращаемое функцией `Тип()` не может быть использовано.

**Воспроизведение ошибки**
1.
```bsl
#native
ТипЧ = ТипЗнч(2);
ТипМ = Тип("Массив");
Рез = (ТипЧ<>ТипМ);
Сообщить(Рез);
```
```
{Модуль C:\_lab\OneScript2\native-t2.os / Ошибка в строке: 4,5 / Ошибка компиляции статического модуля
OneScript.Compilation.CompilerException: {Модуль C:\_lab\OneScript2\native-t2.os / Ошибка в строке: 4,14 / Преобразование из типа OneScript.Types.TypeDescriptor в тип BslValue не поддерживается}
Рез = (ТипЧ<>ТипМ);
   at OneScript.Language.ThrowingErrorSink.AddError(CodeError err) in C:\_Repo\OneScript\src\OneScript.Language\ThrowingErrorSink.cs:line 33
   at OneScript.Native.Compiler.ExpressionTreeGeneratorBase.AddError(BilingualString errorText, CodeRange location) in C:\_Repo\OneScript\src\OneScript.Native\Compiler\ExpressionTreeGeneratorBase.cs:line 65
   at OneScript.Native.Compiler.MethodCompiler.AddError(BilingualString errorText, CodeRange location) in C:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 1517
   at OneScript.Native.Compiler.MethodCompiler.CompileBinaryOp(Expression left, Expression right, BinaryOperationNode binaryOperationNode) in C:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 656
   at OneScript.Native.Compiler.MethodCompiler.VisitBinaryOperation(BinaryOperationNode binaryOperationNode) in C:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 476
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.<CreateVisitors>b__2_2(BslSyntaxNode x) in C:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 37
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node) in C:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 490
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitExpression(BslSyntaxNode expression) in C:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 227
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitAssignmentRightPart(BslSyntaxNode node) in C:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 179
   at OneScript.Native.Compiler.MethodCompiler.VisitAssignment(BslSyntaxNode assignment) in C:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 409
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.DefaultVisit(BslSyntaxNode node) in C:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 490
   at OneScript.Language.SyntaxAnalysis.BslSyntaxWalker.VisitStatement(BslSyntaxNode statement) in C:\_Repo\OneScript\src\OneScript.Language\SyntaxAnalysis\BslSyntaxWalker.cs:line 162
   at OneScript.Native.Compiler.MethodCompiler.VisitStatement(BslSyntaxNode statement) in C:\_Repo\OneScript\src\OneScript.Native\Compiler\MethodCompiler.cs:line 178}
```
**Ожидаемое поведение**
_Да_

2.
```bsl
#native
ТипМ = Тип("Массив");
Сообщить(ТипМ);
Сообщить(ТипЗнч(ТипМ));
```
```
{Модуль C:\_lab\OneScript2\native-t3.os / Ошибка в строке: 4,9 / Преобразование из типа OneScript.Types.TypeDescriptor в тип BslValue не поддерживается}
```
Стектрейса нет.
**Ожидаемое поведение**
_Массив
Тип_

**Окружение**
 - Версия: develop

**Comment by EvilBeaver** [comment]
@Mr-Rm чтобы не делать двойную работу: я могу это себе взять или ты хочешь починить?

**Comment by Mr-Rm** [comment]
Есть готовый фикс.
