### ISSUE TITLE
v2 native: Передача параметров по значению в методы библиотечных объектов

### ISSUE THREAD

**Issue by Mr-Rm** [EvilBeaver/OneScript#1303]
**Опишите ошибку**
В режиме ` native` передача параметров всегда выполняется по значению. При этом не работают методы объектов стандартной библиотеки, которые возвращают значения через переданный параметр.

**Воспроизведение ошибки**
```bsl
#native
Ст = Новый Структура("Поле1", 1);
Зн = ""; // может быть любого типа или объявлена как 'Перем Зн' в начале модуля
Рез = Ст.Свойство("Поле1", Зн);
Сообщить("Рез="+Рез+", зн="+Зн);
```
Ошибка:
```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'OneScript.Contexts.IVariable'.
   at lambda_method18(Closure , NativeClassInstanceWrapper , BslValue[] )
   at OneScript.Native.Runtime.CallableMethod.Invoke(Object target, BslValue[] args) in c:\_Repo\OneScript\src\OneScript.Native\Runtime\CallableMethod.cs:line 46
   at OneScript.Native.Runtime.NativeExecutorProvider.Executor(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments) in c:\_Repo\OneScript\src\OneScript.Native\Runtime\NativeExecutorProvider.cs:line 45
   at OneScript.Execution.ExecutionDispatcher.Execute(BslObjectValue target, IExecutableModule module, BslMethodInfo method, IValue[] arguments) in c:\_Repo\OneScript\src\OneScript.Core\Execution\ExecutionDispatcher.cs:line 43
   at OneScript.Execution.ExecutionExtensions.ExecuteModuleBody(ExecutionDispatcher dispatcher, BslObjectValue target, IExecutableModule module) in c:\_Repo\OneScript\src\OneScript.Core\Execution\ExecutionExtensions.cs:line 21
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.OnInstanceCreation() in c:\_Repo\OneScript\src\ScriptEngine\Machine\Contexts\ScriptDrivenObject.cs:line 120
   at ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation() in c:\_Repo\OneScript\src\ScriptEngine\Machine\Contexts\UserScriptContextInstance.cs:line 57
   at ScriptEngine.Machine.Contexts.ScriptDrivenObject.Initialize() in c:\_Repo\OneScript\src\ScriptEngine\Machine\Contexts\ScriptDrivenObject.cs:line 130
   at ScriptEngine.ScriptingEngine.InitializeSDO(ScriptDrivenObject sdo) in c:\_Repo\OneScript\src\ScriptEngine\ScriptingEngine.cs:line 173
   at ScriptEngine.ScriptingEngine.NewObject(IExecutableModule module, ExternalContextData externalContext) in c:\_Repo\OneScript\src\ScriptEngine\ScriptingEngine.cs:line 145
   at ScriptEngine.HostedScript.Process.Start() in c:\_Repo\OneScript\src\ScriptEngine.HostedScript\Process.cs:line 35
```
**Ожидаемое поведение**
_Рез=Да, зн=1_

**Окружение**
- Версия: v2 develop

**Дополнительная информация**
Такая же ошибка для `ФиксированнаяСтруктура` (возможно, что есть и другие объекты).

**Comment by EvilBeaver** [comment]
Да, это известная проблема. Хочется сначала починить ряд более критичных багов, т.к. это не баг, а скорее фича-недоделка

**Comment by Mr-Rm** [comment]
Дополнение к этой же проблеме. 1С позволяет делать так:
```bsl
Ст = Новый Структура("Поле1",  -11);
Рез = Ст.Свойство("Поле1", 12);
```
OneScript v1.8 и v2 в режиме ВМ реагируют на это (в рантайме)
_Внешнее исключение (System.InvalidCastException): Не удалось привести тип объекта "ScriptEngine.Machine.Values.NumberValue" к типу "ScriptEngine.Machine.IVariable".}_
и
_Внешнее исключение (System.InvalidCastException): Unable to cast object of type 'OneScript.Values.BslNumericValue' to type 'OneScript.Contexts.IVariable'.}_
соответственно.
Наверное, такое лучше отсекать ещё при компиляции, хотя возможна такая формально правильная конструкция:
```bsl
Рез = Ст.Свойство("Поле1", ФункцияСПобочнымиЭффектамиВозможноМодифицирующаяСтруктуру(Ст));
```

**Comment by EvilBeaver** [comment]
> Ст.Свойство("Поле1", ФункцияСПобочнымиЭффектамиВозможноМодифицирующаяСтруктуру(Ст));

Ну в целом, это не ошибка. Просто поведение не указано, а так все в пределах синтаксиса. Так же как, например, удаление элементов при итерации по коллекции
