### ISSUE TITLE
OS2 не запускается на OpenSUSE-Tumbleweed

### ISSUE THREAD

**Issue by Bayselonarrend** [EvilBeaver/OneScript#1465]
**Опишите ошибку**
OneScript2 rc5 (независимый) выдает ошибку на OpenSUSE

```
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.String.StartsWith(System.String, System.StringComparison)
   at System.String.StartsWith(System.String)
   at oscript.BehaviorSelector.Select(System.String[])
   at oscript.Program.Main(System.String[])
```

**Окружение**
 - ОС: openSUSE Tumbleweed 20240604 (WSL)
 - Версия: OneScript-2.0.0-rc5-28826946-linux-x64

**Дополнительная информация**
На Ubuntu та же сборка ошибку не выдает
Возможно, это ошибка требует дополнительных действий в системе, а не исправлений движка ¯\_(ツ)_/¯

**Comment by Nivanchenko** [comment]
Кажется это приколюхи суси. Пробовал доставить что-нибудь? Еще предлагают енвы повключать  https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in

**Comment by nixel2007** [comment]
Глупый вопрос. А libicu-то стоит?

**Comment by Bayselonarrend** [comment]
> Глупый вопрос. А libicu-то стоит? 

Ну, видимо нет) Это скорее к тому, нельзя ли это внутрь засунуть

**Comment by nixel2007** [comment]
> Ну, видимо нет

Проверь, пожалуйста, наверняка, а потом уже будем что-то решать.

**Comment by Bayselonarrend** [comment]
>Проверь, пожалуйста, наверняка, а потом уже будем что-то решать.

Не установлен. Установил - заработало

**Comment by EvilBeaver** [comment]
Да, это обязательная штука, без нее dotnet не умеет делать интернационализацию

**Comment by EvilBeaver** [comment]
> нельзя ли это внутрь засунуть

Навскидку - нельзя. Это зависимость платформы, а не движка

**Comment by Bayselonarrend** [comment]
Ок, похоже надо будет тогда просто в депсы пакета прописать

**Comment by EvilBeaver** [comment]
у двойки нет rpm или deb пакета :(

**Comment by Bayselonarrend** [comment]
:(

**Comment by Bayselonarrend** [comment]
>у двойки нет rpm или deb пакета :(

Я [fpm-ом](https://fpm.readthedocs.io/en/latest/getting-started.html#understanding-the-basics-of-fpm) собираю (руби гем). Очень просто, можно один раз строку запуска или файлик написать и из него любые виды пакетов собираются

[Пример на OS](https://github.com/Bayselonarrend/OpenIntegrations/blob/main/ci/os/releasemaker.os#L230C1-L264C1)

**Comment by Bayselonarrend** [comment]
> Кажется это приколюхи суси

На Oracle Linux тоже воспроизводится, есть подозрение, что это на всех RHEL-ах будет

**Comment by EvilBeaver** [comment]
Документировано, как особенность установки на линуксе: https://oscript.io/learn/install#linux
